//
// Created by jeysa nahara on 17/03/2023.
//

#ifndef EJERCICIO_HUESPEDES_SARA_JEYSA_EVALUACION_H
#define EJERCICIO_HUESPEDES_SARA_JEYSA_EVALUACION_H


class Evaluacion {

};


#endif //EJERCICIO_HUESPEDES_SARA_JEYSA_EVALUACION_H
