//
// Created by jeysa nahara on 17/03/2023.
//

#ifndef EJERCICIO_HUESPEDES_SARA_JEYSA_HOGAR_H
#define EJERCICIO_HUESPEDES_SARA_JEYSA_HOGAR_H


class Hogar {

};


#endif //EJERCICIO_HUESPEDES_SARA_JEYSA_HOGAR_H
