//
// Created by jeysa nahara on 17/03/2023.
//

#ifndef EJERCICIO_HUESPEDES_SARA_JEYSA_HUESPED_H
#define EJERCICIO_HUESPEDES_SARA_JEYSA_HUESPED_H


class Huesped {

};


#endif //EJERCICIO_HUESPEDES_SARA_JEYSA_HUESPED_H
